"""Bounded Windows console dispatch for the installed Blender application.

No shell commands, clipboard changes, process termination or privilege changes.
The payload is generated by blender-service.mjs and revokes itself on timeout.
"""
import ctypes
from ctypes import wintypes as W
import json
import os
from pathlib import Path
import sys
import time


class KEYBDINPUT(ctypes.Structure):
    _fields_ = [('wVk', W.WORD), ('wScan', W.WORD), ('dwFlags', W.DWORD),
                ('time', W.DWORD), ('dwExtraInfo', ctypes.c_size_t)]


class MOUSEINPUT(ctypes.Structure):
    _fields_ = [('dx', W.LONG), ('dy', W.LONG), ('mouseData', W.DWORD),
                ('dwFlags', W.DWORD), ('time', W.DWORD), ('dwExtraInfo', ctypes.c_size_t)]


class INPUTUNION(ctypes.Union):
    _fields_ = [('ki', KEYBDINPUT), ('mi', MOUSEINPUT)]


class INPUT(ctypes.Structure):
    _fields_ = [('type', W.DWORD), ('value', INPUTUNION)]


class WindowsConsole:
    def __init__(self):
        self.user = ctypes.WinDLL('user32', use_last_error=True)
        self.kernel = ctypes.WinDLL('kernel32', use_last_error=True)
        self.user.GetForegroundWindow.restype = W.HWND
        self.user.GetWindow.restype = W.HWND
        self.user.GetWindow.argtypes = [W.HWND, W.UINT]
        self.user.GetLastActivePopup.restype = W.HWND
        self.user.GetLastActivePopup.argtypes = [W.HWND]
        self.user.GetWindowThreadProcessId.argtypes = [W.HWND, ctypes.POINTER(W.DWORD)]
        self.kernel.OpenProcess.restype = W.HANDLE
        self.kernel.OpenProcess.argtypes = [W.DWORD, W.BOOL, W.DWORD]
        self.kernel.CloseHandle.argtypes = [W.HANDLE]
        self.kernel.QueryFullProcessImageNameW.argtypes = [W.HANDLE, W.DWORD, W.LPWSTR, ctypes.POINTER(W.DWORD)]
        self.user.SendInput.argtypes = [W.UINT, ctypes.POINTER(INPUT), ctypes.c_int]
        self.user.MapVirtualKeyW.argtypes = [W.UINT, W.UINT]
        self.user.VkKeyScanW.argtypes = [W.WCHAR]
        self.user.VkKeyScanW.restype = ctypes.c_short
        for name in ['IsWindowVisible', 'IsWindowEnabled', 'IsIconic', 'SetForegroundWindow']:
            getattr(self.user, name).argtypes = [W.HWND]
        self.user.GetClientRect.argtypes = [W.HWND, ctypes.POINTER(W.RECT)]
        self.user.ClientToScreen.argtypes = [W.HWND, ctypes.POINTER(W.POINT)]
        self.user.ShowWindow.argtypes = [W.HWND, ctypes.c_int]
        self.user.GetWindowTextW.argtypes = [W.HWND, W.LPWSTR, ctypes.c_int]
        self.user.GetClassNameW.argtypes = [W.HWND, W.LPWSTR, ctypes.c_int]
        self.callback_type = ctypes.WINFUNCTYPE(W.BOOL, W.HWND, W.LPARAM)
        self.user.EnumWindows.argtypes = [self.callback_type, W.LPARAM]

    def windows(self, app):
        found = []
        expected = os.path.normcase(os.path.realpath(app))

        @self.callback_type
        def visit(hwnd, _):
            if not self.user.IsWindowVisible(hwnd):
                return True
            pid = W.DWORD(); self.user.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
            process = self.kernel.OpenProcess(0x1000, False, pid.value)
            if not process:
                return True
            try:
                name = ctypes.create_unicode_buffer(32768); length = W.DWORD(len(name))
                if self.kernel.QueryFullProcessImageNameW(process, 0, name, ctypes.byref(length)):
                    if os.path.normcase(os.path.realpath(name.value)) == expected:
                        title = ctypes.create_unicode_buffer(2048)
                        cls = ctypes.create_unicode_buffer(256)
                        self.user.GetWindowTextW(hwnd, title, len(title)); self.user.GetClassNameW(hwnd, cls, len(cls))
                        # Keep secondary windows: a preference/file dialog blocks
                        # dispatch rather than receiving commands meant for a scene.
                        found.append({'hwnd': hwnd, 'pid': pid.value, 'class': cls.value,
                                      'title': title.value, 'owner': self.user.GetWindow(hwnd, 4)})
            finally:
                self.kernel.CloseHandle(process)
            return True
        self.user.EnumWindows(visit, 0)
        return found

    def assert_target(self, window):
        hwnd = window['hwnd']
        if self.user.GetForegroundWindow() != hwnd or not self.user.IsWindowEnabled(hwnd):
            raise RuntimeError('window_focus_changed')
        if self.user.GetLastActivePopup(hwnd) != hwnd:
            raise RuntimeError('blender_dialog_open')
        pid = W.DWORD(); self.user.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
        if pid.value != window['pid']:
            raise RuntimeError('window_identity_changed')

    def activate(self, window):
        if self.user.IsIconic(window['hwnd']):
            self.user.ShowWindow(window['hwnd'], 9)
        self.user.SetForegroundWindow(window['hwnd'])
        time.sleep(0.25)
        self.assert_target(window)
        rect = W.RECT(); self.user.GetClientRect(window['hwnd'], ctypes.byref(rect))
        if rect.right < 600 or rect.bottom < 400:
            raise RuntimeError('blender_window_too_small')
        # Move the pointer into the work area. Do not click/select scene objects.
        point = W.POINT(int(rect.right * 0.35), int(rect.bottom * 0.45))
        self.user.ClientToScreen(window['hwnd'], ctypes.byref(point))
        self.user.SetCursorPos(point.x, point.y)

    def send(self, window, events):
        self.assert_target(window)
        values = (INPUT * len(events))(*events)
        if self.user.SendInput(len(events), values, ctypes.sizeof(INPUT)) != len(events):
            raise RuntimeError('console_input_blocked')

    def chord(self, window, keys):
        # Blender consumes hardware scan codes for shortcuts; virtual keys with
        # a zero scan code can be accepted by Windows but ignored by Blender.
        events = [INPUT(1, INPUTUNION(ki=KEYBDINPUT(0, self.user.MapVirtualKeyW(key, 0), 8, 0, 0))) for key in keys]
        events += [INPUT(1, INPUTUNION(ki=KEYBDINPUT(0, self.user.MapVirtualKeyW(key, 0), 10, 0, 0))) for key in reversed(keys)]
        self.send(window, events)

    def text(self, window, command):
        if not command.isascii() or '\n' in command or '\r' in command or len(command) > 16000:
            raise RuntimeError('invalid_console_command')
        for ch in command:
            encoded = self.user.VkKeyScanW(ch)
            if encoded == -1:
                raise RuntimeError('keyboard_layout_unsupported')
            modifiers = [key for bit, key in [(1, 0x10), (2, 0x11), (4, 0x12)]
                         if (encoded >> 8) & bit]
            self.chord(window, modifiers + [encoded & 255])


def dispatch(app, command, job_path, controller, sleep=time.sleep):
    windows = controller.windows(app)
    if len(windows) > 1:
        return {'ok': False, 'code': 'blender_window_ambiguous'}
    job = json.loads(Path(job_path).read_text(encoding='utf-8'))
    # A cold application's process can exist before its scene window. Wait
    # only for this launch, without ever choosing among multiple windows.
    if job.get('launched') and not windows:
        for _ in range(16):
            if time.time() * 1000 >= job['expiresAt'] or not Path(job['permit']).is_file():
                return {'ok': False, 'code': 'startup_expired'}
            sleep(0.5)
            windows = controller.windows(app)
            if windows:
                break
    if not windows:
        return {'ok': False, 'code': 'blender_window_not_ready'}
    if len(windows) != 1 or windows[0]['owner'] or windows[0]['class'] != 'GHOST_WindowClass':
        return {'ok': False, 'code': 'blender_window_ambiguous'}
    window = windows[0]
    if (time.time() * 1000 >= job['expiresAt'] or not Path(job['permit']).is_file()
            or Path(job['permit']).read_text(encoding='utf-8') != job['nonce']):
        return {'ok': False, 'code': 'startup_expired'}
    job['processId'] = window['pid']
    Path(job_path).write_text(json.dumps(job), encoding='utf-8')
    # Any interrupted input has an unknown outcome. Never replay automatically.
    controller.activate(window)
    if job.get('launched'):
        # Dismiss the welcome overlay only in the instance just opened here.
        # assert_target still rejects an owned/modal dialog before any input.
        controller.chord(window, [0x1B])
        sleep(0.25)
    controller.chord(window, [0x10, 0x73])  # Shift+F4: Python Console.
    sleep(0.5)
    controller.chord(window, [0x11, 0x41])  # Select only the current console input.
    controller.text(window, command)
    controller.chord(window, [0x0D])
    return {'ok': True, 'code': 'console_dispatched', 'processId': window['pid']}


if __name__ == '__main__':
    try:
        if sys.platform != 'win32' or len(sys.argv) != 4:
            raise RuntimeError('unsupported_console_dispatch')
        request = json.loads(Path(sys.argv[2]).read_text(encoding='utf-8'))
        result = dispatch(sys.argv[1], request['command'], sys.argv[3], WindowsConsole())
    except Exception as error:
        result = {'ok': False, 'code': 'console_dispatch_unverified', 'errorType': type(error).__name__}
    print(json.dumps(result))
